### ISSUE TITLE
Possible issue while parsing the Title

### ISSUE THREAD

**Issue by mmarfil** [rmlewisuk/CouchPotatoTV-Server#1]
Hello there, let me start by saying this app looks amazing – too bad I couldn't get it work.

Anyway, I have a guess that something might be happening between lines 28 and 52 of `ShelfGenerator`. 

When I try to load `wanted.php`, it will take up to 2 minutes to display the output in the browser, and in the TV app, it won't even show up. I was only able to Search and see my Notifications.

I wish I could help more, but I'm not experienced with PHP. Either way, if you need more info about this issue, I'd be happy to help/clarify.

**Comment by robflate** [comment]
I had the same problem. It turned out that a film in my watch list (http://www.imdb.com/title/tt0150662/) was causing an error. I removed the film and CouchPotatoTV started working. The films original title is "Fucking Åmål". The ring diacritics on the letter A were causing the error.
